openapi: 3.0.1
info:
  title: feedback api
  description: Api to eventually do BI on the data from responses from Geocoding.
  version: 0.1.4
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /feedback:
    post:
      operationId: createFeedback
      tags:
        - feedback
      summary: creates a new record of a chosen result from Geocoding
      parameters:
        - $ref: '#/components/parameters/token'
        - $ref: '#/components/parameters/xApiKey'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/feedback'
      responses:
        '204':
          description: Feedback has been sent successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
components:
  responses:
    BadRequest:
      description: Invalid Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    Unauthorized:
      description: Please provide a valid token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    NotFound:
      description: Resource Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    Forbidden:
      description: Token is not valid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    InternalError:
      description: Invalid Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  parameters:
    xApiKey:
      name: x-api-key
      in: header
      description: JWT authentication token provided by our team
      schema:
        type: string
    token:
      name: token
      in: query
      description: JWT authentication token provided by our team
      schema:
        type: string
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    feedback:
      type: object
      required:
        - request_id
        - chosen_result_id
        - user_id
      properties:
        request_id:
          type: string
        chosen_result_id:
          type: number
          format: int64
        user_id:
          type: string
