{{- $releaseName := .Release.Name -}}
{{- $chartName := include "feedback-api.name" . -}}
{{- $deploymentFlavor := include "feedback-api.deploymentFlavor" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "feedback-api.fullname" .) }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "feedback-api.environment" . }}
    release: {{ $releaseName }}
    {{- include "feedback-api.labels" . | nindent 4 }}
spec:
  {{- if eq $deploymentFlavor "minikube" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.targetPort }}
      protocol: {{ .Values.env.protocol }}
      name: http
      {{- if eq $deploymentFlavor "minikube" }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
    run: {{ $releaseName }}-{{ $chartName }}
    {{- include "feedback-api.selectorLabels" . | nindent 4 }}
{{- end }}
